name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    # Тут можуть бути кроки для збірки, тестування тощо.

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_SCRET }}
        port: ${{ secrets.SERVER_PORT }} # опціонально, якщо ви не використовуєте стандартний порт 22
        script: |
          cd /var/www/html
          git pull origin main
          # Інші команди, які необхідно виконати після розгортання.
